/**
 * Property 1: QR Code Round-Trip Integrity
 *
 * For any memberId + email, the QR code generated by qrService
 * must encode a JSON payload that round-trips back to the same memberId.
 */

const { fc, test } = require("@fast-check/jest");
const { v4: uuidv4 } = require("uuid");

// ── Inline the QR encode/decode logic (no DB needed) ──────────────
const encodeQRPayload = (memberId, qrId) =>
  JSON.stringify({ memberId, qrId, type: "member-checkin" });

const decodeQRPayload = (raw) => {
  try {
    const parsed = JSON.parse(raw);
    return {
      memberId: parsed.memberId || parsed.id || parsed._id || null,
      qrId:     parsed.qrId    || parsed.qrid || null,
    };
  } catch {
    return {};
  }
};

describe("Property 1: QR Code Round-Trip Integrity", () => {
  // Property: encode → decode must preserve memberId and qrId
  test.prop([
    fc.stringMatching(/^[a-f0-9]{24}$/), // memberId (ObjectId-like)
    fc.uuid(),                                         // qrId (UUID)
  ])("encode → decode preserves memberId and qrId", (memberId, qrId) => {
    const encoded = encodeQRPayload(memberId, qrId);
    const decoded = decodeQRPayload(encoded);
    expect(decoded.memberId).toBe(memberId);
    expect(decoded.qrId).toBe(qrId);
  });

  // Property: encoded payload is always valid JSON
  test.prop([
    fc.stringMatching(/^[a-f0-9]{24}$/),
    fc.uuid(),
  ])("encoded payload is always valid JSON", (memberId, qrId) => {
    const encoded = encodeQRPayload(memberId, qrId);
    expect(() => JSON.parse(encoded)).not.toThrow();
  });

  // Property: decoded payload always has type "member-checkin"
  test.prop([
    fc.stringMatching(/^[a-f0-9]{24}$/),
    fc.uuid(),
  ])("encoded payload always has type member-checkin", (memberId, qrId) => {
    const encoded = encodeQRPayload(memberId, qrId);
    const parsed = JSON.parse(encoded);
    expect(parsed.type).toBe("member-checkin");
  });

  // Property: decoding garbage never throws
  test.prop([fc.string()])("decoding arbitrary string never throws", (raw) => {
    expect(() => decodeQRPayload(raw)).not.toThrow();
  });
});
